# Generated by Django 3.1.4 on 2021-04-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210425_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='like',
        ),
        migrations.AddField(
            model_name='cafe',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='like_cafe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_cafe', to=settings.AUTH_USER_MODEL),
        ),
    ]
