# Generated by Django 3.1.4 on 2021-05-01 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210425_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='favorite',
        ),
        migrations.AddField(
            model_name='cafe',
            name='marked_users',
            field=models.ManyToManyField(blank=True, related_name='marked_cafe', to=settings.AUTH_USER_MODEL),
        ),
    ]
